### PR TITLE
Add jubileumsmiddagsgruppen

### PR DESCRIPTION
**Pull request by Hoidi**

### CODE REVIEW

**Review by molleer — APPROVED** [review]

**Review by 89netraM — APPROVED** [review]

**Comment by Hoidi** [comment]
@89netraM merge my conflict!

**Comment by Hoidi** [comment]
Yö wtf did you actually merge the conflict? I'm scared

**Comment by Hoidi** [comment]
Ah looks like it was fixed

**Comment by 89netraM** [comment]
I resolved the conflict first

**Pull request merged**
