### PR TITLE
Added a background image for sexIT and removed the text already there

### PR DESCRIPTION
**Pull request by KarlssonLucas**
I think this would work, correct me if I'm wrong! Docker is being a pain so I can't try it.

### CODE REVIEW

**Review by Hoidi — APPROVED** [review]
Haven't tried it either but don't see why it shouldn't work hehe :ok_hand:

**Comment by Kaffe-work** [comment]
Image file is 0 bytes?

**Comment by KarlssonLucas** [comment]
Weird, if you view the file you can see the image.

**Comment by Hoidi** [comment]
Don't worry about it was the same on other PRs (#225 for example)

**Comment by Kaffe-work** [comment]
Reasonable github performance improvement i think, was not like this earlier.

**Comment by Hoidi** [comment]
Pretty impressive compression algorithms

**Review by ejohnsson6 — APPROVED** [review]
lgtm

**Pull request merged**
