### PR TITLE
Kaffe dev

### PR DESCRIPTION
**Pull request by Kaffe-work**
fixes a bug in the ranking system, adds another rankign system

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Resolve conflicts pls

**Review by ghost — APPROVED** [review]
LGTM

**Comment by Kaffe-work** [comment]
changes done

**Review by ghost — APPROVED** [review]
after my commit it doesn't just look good, it IS good :3

**Comment by Kaffe-work** [comment]
Could just as well have merged my code from the start, master was broken (???). Works now, anyhow.

**Review by lindskogen — APPROVED** [review]

**Pull request merged**
